version: "3.8"
services:
  db:  
    images: mysql:latest
    environment:
      DATABASE_HOST:
      DATABASE_PORT:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - default
  app:
    image:
    ports:
    -  8081:8086
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/curd?createDatabaseIfNotExist=true
      spring.datasource.username: koyembedu
      spring.datasource.password: Admin@123
    depends on:
      - db
    networks:
      - default
