version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: curd
      MYSQL_USER: koyembedu
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  springboot-app:
    image: curd-application-image
    container_name: curd-application-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/curd?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: koyembedu
      SPRING_DATASOURCE_PASSWORD: Admin@123
    depends_on:
      - mysql
    ports:
    - "8085:8086"

volumes:
  mysql-data:
