version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: curd
      MYSQL_USER: koyembedu
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3305:3306"  
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: curd-image
    container_name: curd-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/curd?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: koyembedu
      SPRING_DATASOURCE_PASSWORD: Admin@123
    depends_on:
      - mysql

volumes:
  mysql-data:

